export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const FETCH_REGISTRATION_TOKEN = 'FETCH_REGISTRATION_TOKEN';
export const OPEN_SIGN_IN_REQUIRED_DIALOG = 'OPEN_SIGN_IN_REQUIRED_DIALOG';
export const CLOSE_SIGN_IN_REQUIRED_DIALOG = 'CLOSE_SIGN_IN_REQUIRED_DIALOG';
export const OPEN_REQUEST_NOTIFICATION_DIALOG = 'OPEN_REQUEST_NOTIFICATION_DIALOG';
export const CLOSE_REQUEST_NOTIFICATION_DIALOG = 'CLOSE_REQUEST_NOTIFICATION_DIALOG';
export const OPEN_FEEDBACK_DIALOG = 'OPEN_FEEDBACK_DIALOG';
export const CLOSE_FEEDBACK_DIALOG = 'CLOSE_FEEDBACK_DIALOG';
export const FORBID_NOTIFICATION = 'FORBID_NOTIFICATION';
export const FETCH_MY_PROFILE = 'FETCH_MY_PROFILE';
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_FINISH = 'REQUEST_FINISH';
export const OPEN_TOAST = 'OPEN_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const OPEN_ISSUE_DIALOG = 'OPEN_ISSUE_DIALOG';
export const CLOSE_ISSUE_DIALOG = 'CLOSE_ISSUE_DIALOG';

export const PICK_UP_MAP = 'PICK_UP_MAP';
export const FETCH_MY_MAPS = 'FETCH_MY_MAPS';
export const FETCH_FOLLOWING_MAPS = 'FETCH_FOLLOWING_MAPS';
export const CREATE_MAP = 'CREATE_MAP';
export const EDIT_MAP = 'EDIT_MAP';
export const DELETE_MAP = 'DELETE_MAP';
export const LOAD_MY_MAPS_START = 'LOAD_MY_MAPS_START';
export const LOAD_MY_MAPS_END = 'LOAD_MY_MAPS_END';
export const LOAD_FOLLOWING_MAPS_START = 'LOAD_FOLLOWING_MAPS_START';
export const LOAD_FOLLOWING_MAPS_END = 'LOAD_FOLLOWING_MAPS_END';
export const SELECT_MAP = 'SELECT_MAP';
export const FETCH_RECENT_REVIEWS = 'FETCH_RECENT_REVIEWS';
export const LOAD_RECENT_REVIEWS_START = 'LOAD_RECENT_REVIEWS_START';
export const LOAD_RECENT_REVIEWS_END = 'LOAD_RECENT_REVIEWS_END';
export const FETCH_POSTABLE_MAPS = 'FETCH_POSTABLE_MAPS';
export const FETCH_ACTIVE_MAPS = 'FETCH_ACTIVE_MAPS';
export const LOAD_ACTIVE_MAPS_START = 'LOAD_ACTIVE_MAPS_START';
export const LOAD_ACTIVE_MAPS_END = 'LOAD_ACTIVE_MAPS_END';
export const FETCH_RECENT_MAPS = 'FETCH_RECENT_MAPS';
export const LOAD_RECENT_MAPS_START = 'LOAD_RECENT_MAPS_START';
export const LOAD_RECENT_MAPS_END = 'LOAD_RECENT_MAPS_END';
export const FETCH_POPULAR_MAPS = 'FETCH_POPULAR_MAPS';
export const LOAD_POPULAR_MAPS_START = 'LOAD_POPULAR_MAPS_START';
export const LOAD_POPULAR_MAPS_END = 'LOAD_POPULAR_MAPS_END';
export const OPEN_CREATE_MAP_DIALOG = 'OPEN_CREATE_MAP_DIALOG';
export const CLOSE_CREATE_MAP_DIALOG = 'CLOSE_CREATE_MAP_DIALOG';

export const SWITCH_MY_MAPS = 'SWITCH_MY_MAPS';
export const SWITCH_FOLLOWING_MAPS = 'SWITCH_FOLLOWING_MAPS';

export const OPEN_PLACE_SELECT_DIALOG = 'OPEN_PLACE_SELECT_DIALOG';
export const CLOSE_PLACE_SELECT_DIALOG = 'CLOSE_PLACE_SELECT_DIALOG';
export const SELECT_PLACE_FOR_REVIEW = 'SELECT_PLACE_FOR_REVIEW';
export const OPEN_EDIT_REVIEW_DIALOG = 'OPEN_EDIT_REVIEW_DIALOG';
export const CLOSE_EDIT_REVIEW_DIALOG = 'CLOSE_EDIT_REVIEW_DIALOG';
export const OPEN_DELETE_REVIEW_DIALOG = 'OPEN_DELETE_REVIEW_DIALOG';
export const CLOSE_DELETE_REVIEW_DIALOG = 'CLOSE_DELETE_REVIEW_DIALOG';
export const OPEN_EDIT_MAP_DIALOG = 'OPEN_EDIT_MAP_DIALOG';
export const CLOSE_EDIT_MAP_DIALOG = 'CLOSE_EDIT_MAP_DIALOG';
export const OPEN_COPY_REVIEW_DIALOG = 'OPEN_COPY_REVIEW_DIALOG';
export const CLOSE_COPY_REVIEW_DIALOG = 'CLOSE_COPY_REVIEW_DIALOG';
export const OPEN_DELETE_MAP_DIALOG = 'OPEN_DELETE_MAP_DIALOG';
export const CLOSE_DELETE_MAP_DIALOG = 'CLOSE_DELETE_MAP_DIALOG';
export const SELECT_SPOT = 'SELECT_SPOT';
export const OPEN_SPOT_CARD = 'OPEN_SPOT_CARD';
export const CLOSE_SPOT_CARD = 'CLOSE_SPOT_CARD';
export const FETCH_SPOT = 'FETCH_SPOT';
export const FETCH_SPOT_REVIEWS = 'FETCH_SPOT_REVIEWS';
export const FETCH_COLLABORATORS = 'FETCH_COLLABORATORS';
export const FETCH_MAP_REVIEWS = 'FETCH_MAP_REVIEWS';
export const JOIN_MAP = 'JOIN_MAP';
export const LEAVE_MAP = 'LEAVE_MAP';
export const CLEAR_MAP_STATE = 'CLEAR_MAP_STATE';
export const OPEN_REVIEW_DIALOG = 'OPEN_REVIEW_DIALOG';
export const CLOSE_REVIEW_DIALOG = 'CLOSE_REVIEW_DIALOG';
export const SWITCH_SUMMARY = 'SWITCH_SUMMARY';
export const SWITCH_MAP = 'SWITCH_MAP';
export const OPEN_LEAVE_MAP_DIALOG = 'OPEN_LEAVE_MAP_DIALOG';
export const CLOSE_LEAVE_MAP_DIALOG = 'CLOSE_LEAVE_MAP_DIALOG';

export const GET_CURRENT_POSITION = 'GET_CURRENT_POSITION';
export const REQUEST_CURRENT_POSITION = 'REQUEST_CURRENT_POSITION';
export const REQUEST_MAP_CENTER = 'REQUEST_MAP_CENTER';
export const FETCH_SPOTS = 'FETCH_SPOTS';
export const REQUEST_ROUTE = 'REQUEST_ROUTE';
export const G_MAP_MOUNTED = 'G_MAP_MOUNTED';
export const MAP_ZOOM_CHANGED = 'MAP_ZOOM_CHANGED';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const EDIT_REVIEW = 'EDIT_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const FETCH_REVIEWS = 'FETCH_REVIEWS';
export const FETCH_MORE_REVIEWS = 'FETCH_MORE_REVIEWS';
export const LOAD_REVIEWS_START = 'LOAD_REVIEWS_START';
export const LOAD_REVIEWS_END = 'LOAD_REVIEWS_END';
export const LOAD_MORE_REVIEWS_START = 'LOAD_MORE_REVIEWS_START';
export const LOAD_MORE_REVIEWS_END = 'LOAD_MORE_REVIEWS_END';

export const OPEN_DELETE_ACCOUNT_DIALOG = 'OPEN_DELETE_ACCOUNT_DIALOG';
export const CLOSE_DELETE_ACCOUNT_DIALOG = 'CLOSE_DELETE_ACCOUNT_DIALOG';

export const SEARCH_PLACES = 'SEARCH_PLACES';
export const LOAD_PLACES_START = 'LOAD_PLACES_START';
export const LOAD_PLACES_END = 'LOAD_PLACES_END';
export const SEARCH_MAPS = 'SEARCH_MAPS';
export const LOAD_MAPS_START = 'LOAD_MAPS_START';
export const LOAD_MAPS_END = 'LOAD_MAPS_END';

export const LIKE_REVIEW = 'LIKE_REVIEW';
export const UNLIKE_REVIEW = 'UNLIKE_REVIEW';
export const FETCH_REVIEW_LIKES = 'FETCH_REVIEW_LIKES';
export const OPEN_LIKES_DIALOG = 'OPEN_LIKES_DIALOG';
export const CLOSE_LIKES_DIALOG = 'CLOSE_LIKES_DIALOG';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';

export const LOAD_SPOT_START = 'LOAD_SPOT_START';
export const LOAD_SPOT_END = 'LOAD_SPOT_END';
export const CLEAR_SPOT_STATE = 'CLEAR_SPOT_STATE';

export const SELECT_REVIEW = 'SELECT_REVIEW';
export const LOAD_REVIEW_START = 'LOAD_REVIEW_START';
export const LOAD_REVIEW_END = 'LOAD_REVIEW_END';
export const CLEAR_REVIEW_STATE = 'CLEAR_REVIEW_STATE';

export const OPEN_INVITE_TARGET_DIALOG = 'OPEN_INVITE_TARGET_DIALOG';
export const CLOSE_INVITE_TARGET_DIALOG = 'CLOSE_INVITE_TARGET_DIALOG';
export const FETCH_USERS = 'FETCH_USERS';
export const LOAD_USERS_START = 'LOAD_USERS_START';
export const LOAD_USERS_END = 'LOAD_USERS_END';

export const OPEN_SEARCH_MAPS_DIALOG = 'OPEN_SEARCH_MAPS_DIALOG';
export const CLOSE_SEARCH_MAPS_DIALOG = 'CLOSE_SEARCH_MAPS_DIALOG';

export const FETCH_INVITES = 'FETCH_INVITES';
export const LOAD_INVITES_START = 'LOAD_INVITES_START';
export const LOAD_INVITES_END = 'LOAD_INVITES_END';

export const OPEN_BASE_SELECT_DIALOG = 'OPEN_BASE_SELECT_DIALOG';
export const CLOSE_BASE_SELECT_DIALOG = 'CLOSE_BASE_SELECT_DIALOG';
export const SELECT_MAP_BASE = 'SELECT_MAP_BASE';

export const FETCH_TRENDING_SPOTS = 'FETCH_TRENDING_SPOTS';
export const LOAD_TRENDING_SPOTS_START = 'LOAD_TRENDING_SPOTS_START';
export const LOAD_TRENDING_SPOTS_END = 'LOAD_TRENDING_SPOTS_END';

export const LOAD_NOTIFICATIONS_START = 'LOAD_NOTIFICATIONS_START';
export const LOAD_NOTIFICATIONS_END = 'LOAD_NOTIFICATIONS_END';

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const LOAD_USER_REVIEWS_START = 'LOAD_USER_REVIEWS_START';
export const LOAD_USER_REVIEWS_END = 'LOAD_USER_REVIEWS_END';
export const LOAD_MORE_USER_REVIEWS_START = 'LOAD_MORE_USER_REVIEWS_START';
export const LOAD_MORE_USER_REVIEWS_END = 'LOAD_MORE_USER_REVIEWS_END';
export const FETCH_USER_REVIEWS = 'FETCH_USER_REVIEWS';
export const FETCH_MORE_USER_REVIEWS = 'FETCH_MORE_USER_REVIEWS'
export const CLEAR_PROFILE_STATE = 'CLEAR_PROFILE_STATE';
export const FETCH_USER_MAPS = 'FETCH_USER_MAPS';
export const LOAD_USER_MAPS_START = 'LOAD_USER_MAPS_START';
export const LOAD_USER_MAPS_END = 'LOAD_USER_MAPS_END';
export const OPEN_EDIT_PROFILE_DIALOG = 'OPEN_EDIT_PROFILE_DIALOG';
export const CLOSE_EDIT_PROFILE_DIALOG = 'CLOSE_EDIT_PROFILE_DIALOG';

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const LOCATION_CHANGE = 'LOCATION_CHANGE';
