FROM node:8.2.1

RUN mkdir /qoodish-web
WORKDIR /qoodish-web
ADD . /qoodish-web

ARG AWS_REGION
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY
ARG SLACK_WEBHOOK
ARG SLACK_CHANNEL
ARG S3_BUCKET_ASSETS

ENV AWS_REGION $AWS_REGION
ENV AWS_ACCESS_KEY $AWS_ACCESS_KEY
ENV AWS_SECRET_KEY $AWS_SECRET_KEY
ENV SLACK_WEBHOOK $SLACK_WEBHOOK
ENV SLACK_CHANNEL $SLACK_CHANNEL
ENV S3_BUCKET_ASSETS $S3_BUCKET_ASSETS

RUN yarn
RUN yarn build:prod
RUN yarn upload
