name: Dev
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master
concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true
env:
  PROJECT_ID: qoodish-dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: |
          pnpm install
      - name: Lint
        run: |
          pnpm lint
      - name: Biome check
        run: |
          pnpm biome ci ./src
  deploy:
    if: github.event_name == 'push'
    needs:
      - lint
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Decrypt secrets
        run: |
          gcloud secrets versions access latest \
            --secret=QOODISH_WEB_DOTENV \
            --project=$PROJECT_ID \
            --out-file=.env.local
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: |
          pnpm install
      - name: Deploy to Cloudflare Workers
        run: |
          CLOUDFLARE_API_TOKEN="$(gcloud secrets versions access latest \
            --secret=QOODISH_WEB_CLOUDFLARE_API_TOKEN \
            --project=$PROJECT_ID)"
          echo "::add-mask::$CLOUDFLARE_API_TOKEN"
          export CLOUDFLARE_API_TOKEN
          pnpm run deploy:dev
