name: Dev
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  PROJECT_ID: qoodish-dev
  SERVICE_NAME: qoodish-web
  ARTIFACT_REGISTRY: asia-northeast1-docker.pkg.dev
  BRANCH_NAME: ${{ github.head_ref }}
jobs:
  build-image:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
      - name: Prettier
        run: |
          yarn prettier --check "**/*.{ts,tsx,js}"
      - name: yarn build
        run: |
          yarn build
        env:
          NEXT_PUBLIC_ENDPOINT: https://dev.qoodish.com
          NEXT_PUBLIC_API_ENDPOINT: https://api-dev.qoodish.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: qoodish-dev
          NEXT_PUBLIC_FIREBASE_APP_ID: 1:412705999417:web:eb2eaa0a4d7976474adbe8
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_DEV }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: auth-dev.qoodish.com
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: qoodish-dev.appspot.com
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 412705999417
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: G-DTEPY35ZS7
          NEXT_PUBLIC_VAPID_KEY: ${{ secrets.NEXT_PUBLIC_VAPID_KEY_DEV }}
          NEXT_PUBLIC_CLOUD_STORAGE_ENDPOINT: https://storage.googleapis.com
          NEXT_PUBLIC_GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY_DEV }}
          NEXT_PUBLIC_GOOGLE_STATIC_MAP_URL: https://maps.googleapis.com/maps/api/staticmap?key=${{ secrets.GOOGLE_MAP_API_KEY_DEV }}
          NEXT_PUBLIC_FB_APP_ID: 455361741334663
          NEXT_PUBLIC_PICKED_UP_MAP_ID: 1
      - run: |
          gcloud auth configure-docker $ARTIFACT_REGISTRY --quiet
      - name: Build image
        run: |
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from $ARTIFACT_REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$BRANCH_NAME \
            -t $ARTIFACT_REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA \
            -t $ARTIFACT_REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$BRANCH_NAME \
            .
        env:
          DOCKER_BUILDKIT: 1
      - name: Push image
        run: |
          docker push -a $ARTIFACT_REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME
  deploy:
    needs:
      - build-image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Deploy revision
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
          CLOUD_RUN_SA_NAME: dev-qoodish-web@qoodish-common.iam.gserviceaccount.com
          SITE_DOMAIN: dev.qoodish.com
          RENDERTRON_ENDPOINT: https://rendertron-dev.qoodish.com
        run: |
          gcloud beta run deploy $SERVICE_NAME \
            --platform=managed \
            --region=asia-northeast1 \
            --project=$PROJECT_ID \
            --cpu=1000m \
            --memory=256Mi \
            --port=8080 \
            --service-account=$CLOUD_RUN_SA_NAME \
            --ingress=all \
            --allow-unauthenticated \
            --image=$ARTIFACT_REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA \
            --set-env-vars "NODE_ENV=production" \
            --set-env-vars "SITE_DOMAIN=$SITE_DOMAIN" \
            --set-env-vars "RENDERTRON_ENDPOINT=$RENDERTRON_ENDPOINT"
