name: Dev
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  PROJECT_ID: qoodish-dev
  SERVICE_NAME: qoodish-web
  ARTIFACT_REGISTRY: asia-northeast1-docker.pkg.dev
  BRANCH_NAME: ${{ github.head_ref }}
jobs:
  build-image:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Decrypt secrets
        run: |
          gcloud secrets versions access latest \
            --secret=QOODISH_WEB_DOTENV \
            --project=$PROJECT_ID \
            --out-file=.env.local
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.6
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: |
          pnpm install
      - name: Lint
        run: |
          pnpm lint
      - name: Biome check
        run: |
          pnpm biome ci ./src
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACT_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ARTIFACT_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.GITHUB_SHA }}
          tags: |
            type=ref,event=pr,prefix=pr-,suffix=
            type=sha,prefix=,suffix=,format=long
      - name: Build and push image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs:
      - build-image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Deploy revision
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
          CLOUD_RUN_SA_NAME: dev-qoodish-web@qoodish-common.iam.gserviceaccount.com
        run: |
          gcloud beta run deploy $SERVICE_NAME \
            --platform=managed \
            --region=asia-northeast1 \
            --project=$PROJECT_ID \
            --cpu=1000m \
            --cpu-boost \
            --memory=512Mi \
            --max-instances=1 \
            --port=8080 \
            --service-account=$CLOUD_RUN_SA_NAME \
            --ingress=all \
            --allow-unauthenticated \
            --execution-environment=gen2 \
            --tag=$BRANCH_NAME \
            --image=$ARTIFACT_REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA \
            --set-env-vars "NODE_ENV=production" \
            --set-env-vars "API_ENDPOINT=https://api-dev.qoodish.com"
